# Generated by Django 4.2.2 on 2023-06-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0003_comment'),
        ('core', '0002_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='candidate',
            field=models.ManyToManyField(blank=True, to='worker.worker'),
        ),
    ]
