# Generated by Django 4.2.2 on 2023-07-03 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category_alter_vacancy_options_vacancy_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vacancy',
            unique_together={('title', 'email')},
        ),
    ]
