# Generated by Django 4.2.2 on 2023-07-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0005_resume_rename_need_salary_worker_waiting_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
